#!/usr/bin/env bash


set -e

terraform force-unlock -force mantispw/mantispw-testnet_core || true

destroy() {
    bitte tf $1 plan --destroy
    bitte tf $1 apply
}

destroy clients
destroy consul
destroy core
destroy network

# aws s3 rm --recursive s3://iohk-mantispw-bitte/infra/binary-cache
# rm encrypted/*.json encrypted/nix-public-key-file secrets/*
