[package]
name = "syncstat"
version = "0.1.0"
authors = ["Timothy DeHerrera <tim.deherrera@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restson = "^0.7"
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "^1.0"
serde-hex = "0.1.0"
percentage = "0.1.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
anyhow = "1.0.40"

[profile.release]
lto = true
