{
 "title": "Mantis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(client_id)" },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block number / Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Block number" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_number_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Checkpoint block number / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Block number" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_checkpoint_number_gauge_gauge"
    }
   ]
  },
  {
   "title": "Transactions in pool / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "# of transactions" }
   ],
   "targets": [
    {
     "expr": "app_transactions_pool_size_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Ommers in block / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "# of transactions" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_uncles_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Transactions in block / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "# of transactions" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_transactions_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block time / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "block time" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_timeBetweenParent_seconds_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Difficulty / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "Difficulty" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_difficulty_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Gas used / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "gas used" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_gasUsed_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Gas limit / Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "gas limit" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_gasLimit_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "OBFT Federation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Stable Checkpoint in Ledger",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "morpho_checkpoint_stable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Number of Votes for Latest Checkpoint",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Nb Votes" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_nb_votes_latest",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block Number Pushed to Midnight",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_pushed_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Checkpoint in the Stable Ledger",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_stable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Checkpoint in the Unstable Ledger",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_checkpoint_unstable_state_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Latest Checkpoint Candidate fetched from Midnight",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short", "label": "Midnight Block Number" }
     ],
     "targets": [
      {
       "expr": "morpho_midnight_latest_pow_block_number",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "apdex_network_healthy $node",
   "type": "singlestat",
   "description": "Apdex given:\n- satisfied count = sent + received - low - high\n- tolerant count = low\n- total count = sent + received\n",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(increase(app_network_messages_received_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_messages_sent_counter_total{instance=\"$node\"}[$__range])) - sum(increase(app_network_peers_highSeverityOffense_counter_total{instance=\"$node\"}[$__range])) - sum(increase(app_network_peers_lowSeverityOffense_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_peers_lowSeverityOffense_counter_total{instance=\"$node\"}[$__range])) / 2) / (sum(increase(app_network_messages_received_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_network_messages_sent_counter_total{instance=\"$node\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Blacklisted peers $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "app_network_peers_blacklisted_gauge{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Discovered peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {
     "expr": "app_network_discovery_foundPeers_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming total peers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming handshaked peers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_incoming_handshaked_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming pending peers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_incoming_total_gauge - app_network_peers_incoming_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing total peers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ]
  },
  {
   "title": "Outgoing handshaked peers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_outgoing_handshaked_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing pending peers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "number of peers" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_outgoing_total_gauge - app_network_peers_outgoing_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none", "label": "number of messages" }
   ],
   "targets": [
    {
     "expr": "increase(app_network_messages_sent_counter_total_counter{namespace=\"$namespace\"}[$__range])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Messages received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none", "label": "number of messages" }
   ],
   "targets": [
    {
     "expr": "increase(app_network_messages_received_counter_total_counter{namespace=\"$namespace\"}[$__range])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "PoW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOHK mined blocks",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(app_sync_block_minedBlocks_counter_total[$__range]))"
      }
     ]
    },
    {
     "title": "Mined blocks (not all mined blocks end up included in the chain)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "number of blocks" }
     ],
     "targets": [
      {
       "expr": "increase(app_sync_block_minedBlocks_counter_total[$__range])    ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mined blocks rate ($node)",
     "type": "singlestat",
     "description": "mined blocks / total blocks in the chain * 100",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(increase(app_sync_block_minedBlocks_counter_total{instance=\"$node\"}[$__range]))) / (sum(increase(app_sync_block_minedBlocks_counter_total[$__range]))) * 100"
      }
     ]
    },
    {
     "title": "Is Mining?",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Hashrate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none", "label": "hashes/s" }
     ],
     "targets": [
      { "expr": "midnight_node_miner_hashrate", "legendFormat": "{{alias}}" }
     ]
    }
   ]
  },
  { "title": "$node | General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Start time $node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 89 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds_gauge{client_id=\"$node\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 89 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds_gauge{client_id=\"$node\"}*1000"
    }
   ]
  },
  {
   "title": "Latest block number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 89 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "app_sync_block_number_gauge_gauge{client_id=\"$node\"}"
    }
   ]
  },
  {
   "title": "AVG Block time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 89 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "app_sync_block_timeBetweenParent_seconds_gauge_gauge{client_id=\"$node\"}"
    }
   ]
  },
  {
   "title": "Latest block time",
   "type": "singlestat",
   "description": "Time between latest imported block and its parent",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 89 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "app_sync_block_timeBetweenParent_seconds_gauge_gauge{client_id=\"$node\"}"
    }
   ]
  },
  {
   "title": "Latest checkpoint block number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 91 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(app_sync_block_checkpoint_number_gauge{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(logback_appender_total_counter{client_id=\"$node\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "apdex_RPC responses",
   "type": "singlestat",
   "description": "- Apdex RPC_responses = (SatisfiedCount + ToleratingCount / 2) / TotalSamples\n\nSatisfiedCount = MethodsSuccessCounter\nToleratingCount = MethodsErrorCounter\nTotalSamples = MethodsSuccessCounter + MethodsErrorCounter + MethodsExceptionCounter",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 93 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) / 2) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))",
     "legendFormat": "apdex_rpc_responses"
    }
   ]
  },
  {
   "title": "rpc_error_responses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 93 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))) * 100",
     "legendFormat": "rpc_error_responses"
    }
   ]
  },
  {
   "title": "rpc_fatal_errors_responses",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 95 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])) / (sum(increase(app_json_rpc_methods_success_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_error_counter_total{instance=\"$node\"}[$__range])) + sum(increase(app_json_rpc_methods_exception_counter_total{instance=\"$node\"}[$__range])))) * 100",
     "legendFormat": "rpc_fatal_errors_responses"
    }
   ]
  },
  { "title": "$node | JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used_gauge{client_id=~\"$node\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state_gauge{client_id=\"$node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current_gauge{client_id=\"$node\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon_gauge{client_id=\"$node\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used_gauge{client_id=\"$node\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_gauge{client_id=~\"$node\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{client_id=\"$node\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{client_id=\"$node\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds_gauge{client_id=\"$node\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds_gauge{client_id=\"$node\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}