{
 "title": "[AUX] Mantis Node [mantis-ops]",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "FastSync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pivot Block",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_block_pivotBlock_number_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Total Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_state_totalNodes_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Downloaded Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_state_downloadedNodes_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Best Full Block",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_block_bestFullBlock_number_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Best Header",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "app_fastsync_block_bestHeader_number_gauge_gauge",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Mantis Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_number_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_transactions_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(app_sync_block_timeBetweenParent_seconds_gauge_gauge{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_difficulty_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block Gas Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_gasLimit_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block Gas Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_gasUsed_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Transactions Pool Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_transactions_pool_size_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Discovery Found Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_discovery_foundPeers_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Discovery Blacklisted Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_blacklisted_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_incoming_handshaked_gauge_gauge{namespace=\"$namespace\"}\n",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_outgoing_handshaked_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(app_json_rpc_methods_error_counter_total_counter{namespace=\"$namespace\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "RPC Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(app_json_rpc_methods_exception_counter_total_counter{namespace=\"$namespace\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "RPC Not Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_json_rpc_notfound_calls_counter_total_counter{namespace=\"$namespace\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "RPC Max Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(app_json_rpc_methods_timer_seconds_max_gauge{namespace=\"$namespace\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (increase(logback_appender_total_counter{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pending Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_pending_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}