{
 "title": "Morpho",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Morpho Checkpoint Unstable State PoW Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_unstable_state_pow_block_number_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Morpho Checkpoint Stable State PoW Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_stable_state_pow_block_number_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Morpho Latest PoW Block Number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "morpho_latest_pow_block_number_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Morpho Checkpoint Pushed PoW Block Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_pushed_pow_block_number_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Mantis Block number / Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_number_gauge_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Mantis Sync Block Checkpoint Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_checkpoint_number_gauge_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Morpho Checkpoint NB Votes Latest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "morpho_checkpoint_nb_votes_latest_gauge",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}